config/routes.rb
Rails.application.routes.draw do
  resources :tests do
    collection do
      delete 'reset'
      get 'export'
    end

    member do
      get 'perform'
    end

    resources :results do
      collection do
        delete 'destroy_all'
      end
    end
  end

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :test

  default_scope { order('id DESC') }

  before_create :set_deltas


  def set_deltas

    self.webview_to_native_delta = (native_received_at.to_f - webview_started_at.to_f)
    self.webview_to_native_delta = -1.0 if native_received_at.nil?

    self.native_to_webview_delta = (webview_received_at.to_f - native_started_at.to_f)
    self.native_to_webview_delta = -1.0 if webview_received_at.nil?

  end

  def native_to_webview_ms_delta
    native_to_webview_delta * 1000
  end

  def webview_to_native_ms_delta
    webview_to_native_delta * 1000
  end

end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_test_and_result, only: [:edit, :update, :destroy]
  before_action :set_test, only: [:index, :create, :destroy_all, :show]

  def index
    @results = @test.results
  end

  def create
    @result = @test.results.build result_params

    respond_to do |format|
      if @result.save
        format.html { render text: 'k.' }
        format.json { render json: {}, status: :created }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
  end

  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to edit_test_result_path(@test, @result), notice: 'Result was successfully updated.' }
        format.json { render json: {}, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_all
    @test.results.destroy_all
    respond_to do |format|
      format.html { redirect_to test_results_url(@test), notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_and_result
      @test = set_test
      @result = @test.results.find(params[:id])
    end

    def set_test
      @test = Test.find(params[:test_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(
        :webview_started_at, :native_received_at, :native_started_at, :webview_received_at,
        :webview_payload_length, :native_payload_length,
        :from,
        :fps,
        :method_name,
        :cpu, :mem,
        :render_paused,
        :agent)
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy, :perform]

  def export
    export_name = params[:name]

    if export_name
      system("rm tmp/export.zip")
      system("rm tmp/*.csv") # dyno might stay the same
      system("rm tmp/*.txt")

      system("ruby export.rb #{params[:name]}")
      system("zip -pr tmp/export.zip tmp/*.csv tmp/*.txt")
      send_file("tmp/export.zip", :type => "application/zip")
    else
      render :text => "name param missing"
    end
  end

  def reset
    system("rake db:migrate VERSION=0")
    system("rake db:migrate")
    #system("rake db:setup")
  end


  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  def perform
    unless @test
      render "all_done"
    else

    method, amount, interval, payload, direction = @test.name.split('-')

    redirect_to test_results_path(@test, {
      direction: direction,
      method: method,
      amount: amount,
      interval: interval,
      payload: payload,
      next_test_id: (@test.id + 1)
      })
    end

  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Benchmark</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink="pls">

<div id="indicator">
  INDICATOR
</div>

<a href="javascript:history.back()">Back</a> | <%= link_to "test index", tests_path %>

<%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/results/_form.html.erb
<% url = if params[:action] == "new"
test_results_path(@test)
else
  test_result_path(@test, @result)
end
%>
<%= form_for(@result, :url => url ) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :test_id %><br>
    <%= f.text_field :test_id %>
  </div>
  <div class="field">
    <%= f.label :native_started_at %><br>
    <%= f.datetime_select :native_started_at %>
  </div>
  <div class="field">
    <%= f.label :native_received_at %><br>
    <%= f.datetime_select :native_received_at %>
  </div>

  <div class="field">
    <%= f.label :webview_started_at %><br>
    <%= f.datetime_select :webview_started_at %>
  </div>
  <div class="field">
    <%= f.label :webview_received_at %><br>
    <%= f.datetime_select :webview_received_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', test_result_path(@test, @result) %> |
<%= link_to 'Back', test_results_path %>

app/views/results/index.html.erb
<script src="http://localhost:31337/WebSocketTest2.js"></script>

<h1 id="renderloop">-1</h1>

<canvas id="myCanvas" width="320" height="200"></canvas>

<button id="toggleScrolling">Toggle scrolling</button>


<fieldset>
  <legend>Configuration</legend>

  <label>Direction</label>
  <select id="directionElem">
    <option value="native">to native</option>
    <option value="webview">to webview</option>
  </select>
  <br/>

  <label>Method</label>
  <select id="methodElem">
    <!-- ordnung -->
    <option value="cookie">cookie (4kb max)</option>

    <option value="localStorage">localStorage</option>

    <option value="http.websockets">http.websockets</option>

    <option value="jscore.sync">jscore.sync</option>
    <option value="webkit.usercontent">webkit.usercontent</option>

    <option value="html.iframe">html.iframe</option>
    <option value="html.iframe.same">html.iframe.same</option>
    <option value="html.iframe.replace">html.iframe.replace</option>

    <option value="html.script">html.script</option>
    <option value="html.script.same">html.script.same</option>
    <option value="html.script.replace">html.script.replace</option>

    <option value="html.svgImage">html.svgImage</option>
    <option value="html.svgImage.same">html.svgImage.same</option>
    <option value="html.svgImage.replace">html.svgImage.replace</option>

    <option value="html.img">html.img</option>
    <option value="html.img.same">html.img.same</option>
    <option value="html.img.replace">html.img.replace</option>

    <option value="html.link">html.link</option>
    <option value="html.link.same">html.link.same</option>
    <option value="html.link.replace">html.link.replace</option>

    <option value="html.embed">html.embed</option>
    <option value="html.embed.same">html.embed.same</option>
    <option value="html.embed.replace">html.embed.replace</option>

    <option value="html.object">html.object</option>
    <option value="html.object.same">html.object.same</option>
    <option value="html.object.replace">html.object.replace</option>

    <option value="xhr.async">xhr.async</option>
    <option value="xhr.sync">xhr.sync</option>

    <option value="a.click">a.click</option>

    <option value="location.href">location.href</option>
    <option value="location.replace">location.replace</option>

    <option value="location.hash">location.hash</option>
    <option value="location.replaceHash">location.replaceHash</option>

    <option value="webview.eval">webview.eval</option>

    <option value="webkit.alert">webkit.alert</option>
    <option value="webkit.prompt">webkit.prompt</option>
    <option value="webkit.confirm">webkit.confirm</option>
    <option value="webkit.title">webkit.title</option>

    <option value="prompt">prompt</option>
    <option value="alert">alert</option>
    <option value="confirm">confirm</option>

    <option value="prompt.pongweb">prompt.pongweb</option>
    <option value="jscore.pongweb">jscore.pongweb</option>

    <option value="xhrget.async">xhrget.async</option>
    <option value="xhrget.sync">xhrget.sync</option>

    <option value="xhrpost.async">xhrpost.async</option>
    <option value="xhrpost.sync">xhrpost.sync</option>

  </select><br/>

  <label>Messages to send</label>
<!--
<input id="messagesElem" type="number" value="1" size="4"></input><br/>
-->

  <select id="messagesElem">
    <option value="1">1</option>
    <option value="20">20</option>

<option value="1">1</option>
<option value="2">2</option>
<option value="1000">1000</option>
    <option value="10">10</option>

    <option value="25">25</option>
    <option value="50">50</option>
  </select><br/>

  <label>Interval length:</label>

<!--
  <input id="intervalLengthElem" type="number" value="250" size="4"></input><br/>
-->

  <select id="intervalLengthElem">
    <option value="50">50</option>

    <option value="500">500</option>

    <option value="100">100</option>

    <option value="25">25</option>

    <option value="1000">1000</option>
    <option value="5000">5000</option>


    <option value="50">50</option>

    <option value="250">250</option>
    <option value="500">500</option>
    <option value="10">10</option>

  </select><br/>


  <label>Payload (n*1024)</label>
<!--
  <input id="payloadLengthElem" type="number" value="0" size="4"></input><br/>
-->

  <select id="payloadLengthElem">

    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>

    <option value="2000">2000</option>
    <option value="3">3</option>
    <option value="1000">1000</option>
    <option value="64">31</option>
    <option value="0">0</option>
    <option value="1">1</option>
    <option value="250">250</option>
    <option value="10">10</option>
    <option value="2000">2000</option>
    <option value="3000">3000</option>
    <option value="4000">4000</option>
    <option value="5000">5000</option>
    <option value="10000">10000</option>
  </select><br/>

  <button id="perform">Perform</button>
  <button id="flush">Flush</button>
</fieldset>

<iframe class="nativebridge" src="about:blank"></iframe>
<embed class="nativebridge" src="about:blank"></embed>
<script class="nativebridge"></script>
<svg xmlns="http://www.w3.org/2000/svg" width="100px" height="100px">
  <image class="nativebridge"></image>
</svg>
<img class="nativebridge" />
<link class="nativebridge" rel="stylesheet" type="text/css" href="#" />
<object class="nativebridge" data="about:blank"></object>


<h1>Listing results</h1>
<%= link_to 'Destroy all results', destroy_all_test_results_path(@test), method: :delete, data: { confirm: 'Are you sure?' } %>

<%= render 'tests/testresults' %>

<table border="1">
  <thead>
    <tr>
      <th>Result</th>
      <th>Method</th>
      <th>from</th>
      <th>fps</th>
      <th>mem</th>
      <th>cpu</th>
      <th>render paused</th>

      <th>webview to native delta</th>
      <th>native to webview delta</th>

      <th>webview payload</th>
      <th>native payload</th>

      <th>WebView start</th>
      <th>Native received</th>
      <th>Native started</th>
      <th>WebView received</th>
      <th>Agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.id %></td>
        <td><%= result.method_name %></td>
        <td><%= result.from %></td>
        <td><%= result.fps %></td>
        <td><%= result.mem %></td>
        <td><%= result.cpu %></td>
        <td><%= result.render_paused %></td>

        <td><%= result.webview_to_native_delta.round(4) %></td>
        <td><%= result.native_to_webview_delta.round(4) %></td>

        <td><%= result.webview_payload_length %></td>
        <td><%= result.native_payload_length %></td>

        <td><%= result.webview_started_at.to_f.round(4) %></td>
        <td><%= result.native_received_at.to_f.round(4) %></td>

        <td><%= result.native_started_at.to_f.round(4) %></td>
        <td><%= result.webview_received_at.to_f.round(4) %></td>

        <td><%= result.agent %></td>

        <td><%= link_to 'Edit', edit_test_result_path(@test, result) %></td>
        <td><%= link_to 'Destroy', test_result_path(@test, result), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>